# -*- coding: utf-8 -*-
"""Balanced Parentheses Check.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jcnm1rZF8bDZBGWDEbPLViAL-917Dua2
"""

def balance_check(s):
  open = ['[', '(', '{']
  closed = [']', ')', '}']
  
  stack = []

  for paren in s:
    if paren in open:
      stack.append(paren)
    
    else:
      if len(stack) == 0:
        return False
      
      last_open = stack.pop()

      if closed[open.index(last_open)] != paren:
        return False
  
          
  return len(stack) == 0
  
  
#balance_check('[(())]')
balance_check('[(())]()')

def balance_check(s):
  if len(s) % 2 != 0:
    return False
  
  opening = set('[({')
  matches = set( [('(',')'), ('[',']'), ('{','}')] )

  stack = []

  for paren in s:
    if paren in opening:
      stack.append(paren)

    else:
      if len(stack) == 0:
        return False

      last_open = stack.pop()

      if (last_open,paren) not in matches:
        return False

  return len(stack) == 0
  
print(balance_check('[()]'))
print(balance_check('[()](]'))