# -*- coding: utf-8 -*-
"""Implementation of a Queue using Two Stacks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tNCL2QFeqKgIzU2mfLIiphq9ZauHJyCs
"""

class Queue2Stacks(object):
    
    def __init__(self):
        
        # Two Stacks
        self.instack = []
        self.outstack = []
     
    def enqueue(self,element):
        
        # Add an enqueue with the "IN" stack
        self.instack.append(element)
    
    def dequeue(self):
        if not self.outstack:
            while self.instack:
                # Add the elements to the outstack to reverse the order when called
                self.outstack.append(self.instack.pop())
        return self.outstack.pop()

q = Queue2Stacks()

q.enqueue(1)
q.enqueue(2)
q.enqueue(3)
print(q.dequeue())