# -*- coding: utf-8 -*-
"""Implement a Stack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xWpRVXbn8-H67jgqJgfrmefsI8cYnCL5
"""

class Stack(object):
  def __init__(self):
    self.items = []

  def enqueue(self, item):
    self.items.append(item)

  def isEmpty(self):
    return self.items == []

  def dequeue(self):
    return self.items.pop()

  def peek(self):
    return self.items[len(self.items)-1]

  def size(self):
    return len(self.items)
s = Stack()

print(s.isEmpty())
s.add(1)
s.add('ola')

print('last item is',s.peek())
print('size is',s.size())

print(s.pop())

print('size is',s.size())