# -*- coding: utf-8 -*-
"""Sentence Reversal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nFCENWheYape05YEQ6oZM7xE7egw8S0-
"""

def rev_word(s):
  s = s.strip().replace('  ',' ').split()
  rev_list = ''

  for word in reversed(s):
    rev_list += word+' '

  return rev_list.strip()

rev_word('   Hello John    how are you   ')

#shorter but not the one interviewe likes, better to use manually funcitions
#instead of this build-in python one
def rev_word1(s):
  return ' '.join(s.split()[::-1])

print(rev_word('   Hello John    how are you   '))

#the best one

def rev_word2(s):
  words = []
  length = len(s)
  i = 0

  while i < length:
    if s[i] != ' ':
      start_word = i
      
      while i < length and s[i] != ' ':
        i += 1
        
      words.append(s[start_word:i])
          
    i += 1
  #return ' '.join(words[::-1])
  
  #custom revert
  rev_list = []
  for word in words:
    rev_list = [word, *rev_list]
  
  return ' '.join(rev_list)

rev_word2('   Hello John    how are you   ')

"""
RUN THIS CELL TO TEST YOUR SOLUTION
"""

from nose.tools import assert_equal

class ReversalTest(object):
    
    def test(self,sol):
        assert_equal(sol('    space before'),'before space')
        assert_equal(sol('space after     '),'after space')
        assert_equal(sol('   Hello John    how are you   '),'you are how John Hello')
        assert_equal(sol('1'),'1')
        print("ALL TEST CASES PASSED")
        
# Run and test
t = ReversalTest()
t.test(rev_word)