# -*- coding: utf-8 -*-
"""Factorial Recursion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lmfzhRN86b1PSEcB_Uwt6V9rKgYU-hD6
"""

def fact(n):
  # Base case
  if n == 0:
    return 1
  else:
    return n * fact(n-1)

fact(5)

def rect_sum(n):
  if n == 0:
    return 0
  else:
    return n + rect_sum(n-1)

rect_sum(5)

def sum_func(n):
  if n == 0:
    return n
  else:
    return n % 10 + sum_func(n // 10)

sum_func(54321)

def word_split(phrase, list_of_words, output=[]):
  word = list_of_words.pop()

  if word not in phrase:
    return []
  else:
    output += [word]
    if list_of_words != []:
      return word_split(phrase, list_of_words, output)
    
  return output

word_split('themanran', ['the','ran','man'])