# -*- coding: utf-8 -*-
"""bubble sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/148DJb_K4BO05x7_Y9t8dEnvmweCgWkKF
"""

def bubble_sort(arr):
  for n in range(len(arr)-1,0,-1):
    for k in range(n):
      
      if arr[k] > arr[k+1]:
        arr[k], arr[k+1] = arr[k+1],arr[k]

  return arr


bubble_sort([30,20,10,50,40])