# -*- coding: utf-8 -*-
"""insersion_sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16jw5AeGwKrX3Tt2crCPcLpze3Eji8Lv_
"""

def insertion_sort(arr):
  for i in range(1, len(arr)):

    currentVal = arr[i]
    position = i

    while position > 0 and arr[position-1] > currentVal:

      arr[position] = arr[position-1]
      position -= 1
    
    arr[position] = currentVal
  return arr

insertion_sort([5,1,6,2,11,8,10,9])