# -*- coding: utf-8 -*-
"""Selection Sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vO6I_Us0bgZX8vY3B3gGp2RhcgFTQcqR
"""

def selection_sort(arr):
  for right in range(len(arr)-1, 0, -1):
    positionOfMax = 0
    
    for left in range(1, right+1):  
      if arr[left] > arr[positionOfMax]:
        positionOfMax = left
    
    arr[positionOfMax], arr[right] = arr[right], arr[positionOfMax]
  return arr

selection_sort([30,20,40,10,50])