# -*- coding: utf-8 -*-
"""Binary Search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pgYTs84FYj7s3soy6YSyOLeeo6y34p0U
"""

def binary_search(arr, target):
  first = 0
  last = len(arr)-1

  found = False

  while first <= last and not found:
    mid = (first + last) // 2

    if arr[mid] == target:
      found = True
    else:
      if target < arr[mid]:
        last = mid-1
      else:
        first = mid+1
  return found


arr = [1,2,3,4,5,6,10,12,14,18,20]

binary_search(arr, 5)